---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "{{ name }}"
      azure_rm_resourcegroup:
        name: "{{ name }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg

- hosts: localhost
  connection: local
  tasks:
    - name: Create VM Extension
      community.azure.azure_rm_virtualmachineextension:
        name: NvidiaGpuDriverWindows
        location: westeurope
        resource_group: 'GPUV4RAF'
        virtual_machine_name: myVM
        publisher: Microsoft.HpcCompute
        virtual_machine_extension_type: NvidiaGpuDriverWindows
        type_handler_version: "1.3"
        settings: '{}'
        auto_upgrade_minor_version: true
